Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  #config.vm.network "private_network", ip: "192.168.1.2"
  # Estou em um ambiente windows, então baixei a ferramenta 'winnfsd' para fazer o diretório compartilhado.
  config.vm.network "private_network", ip: "192.168.56.100"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
  
  config.winnfsd.uid = 1
  config.winnfsd.gid = 1
end
